name       : coeurl
version    : 0.2.1
release    : 2
source     :
    - https://nheko.im/nheko-reborn/coeurl/-/archive/v0.2.1/coeurl-v0.2.1.tar.gz : 099feb59512fdd321f777547f0d4f1fc3c2d919369330f318b8c36dc646c0764
license    : MIT
homepage   : https://nheko-reborn.github.io/
component  : network.im
summary    : A simple async wrapper around CURL for C++
description: |
    A simple async wrapper around CURL for C++
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libevent_core)
    - pkgconfig(spdlog)
clang      : yes
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
