name       : coeurl
version    : 0.3.0
release    : 3
source     :
    - https://nheko.im/nheko-reborn/coeurl/-/archive/v0.3.0/coeurl-v0.3.0.tar.gz : 48b07482364edcbed03e352f6b8b07e327c331eaa45707ad58e62930fa361382
license    : MIT
homepage   : https://nheko-reborn.github.io/
component  : network.im
summary    : A simple async wrapper around CURL for C++
description: |
    A simple async wrapper around CURL for C++
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libevent_core)
    - pkgconfig(spdlog)
clang      : yes
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
